/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Cliente;
import com.formdev.flatlaf.FlatIntelliJLaf;
import Servidor.ControladorVotos;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.*;

import java.util.*;

/**
 *
 * @author Luxzor
 */
public class App extends javax.swing.JFrame {

    /**
     * Creates new form App
     */
     private ControladorVotos controlador;
     
    private Map<String, JLabel> etiquetasContadores;
    
    public App(ControladorVotos controlador) {
        this.controlador = controlador;
        this.etiquetasContadores = new HashMap<>();
        initComponents();
        inicializarProductos();
        agregarAccionesBotonesGraficas();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        contenido = new javax.swing.JPanel();
        tituloPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        producto1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        imgFIQ = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        iFIQ = new javax.swing.JLabel();
        producto2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        imgFMAT = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        iFMAT = new javax.swing.JLabel();
        producto3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        imgFi = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        iFI = new javax.swing.JLabel();
        btnVGraficoBarra = new javax.swing.JButton();
        btnVGraficoPastel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("VistaApp");
        setLocation(new java.awt.Point(0, 0));
        setSize(new java.awt.Dimension(400, 300));

        tituloPanel.setBackground(new java.awt.Color(204, 255, 255));

        jLabel2.setFont(new java.awt.Font("Montserrat", 1, 20)); // NOI18N
        jLabel2.setText("Vota por tu cafeteria preferida");

        jLabel1.setBackground(new java.awt.Color(204, 255, 255));
        jLabel1.setFont(new java.awt.Font("Montserrat", 1, 28)); // NOI18N
        jLabel1.setText("Votación de productos");

        javax.swing.GroupLayout tituloPanelLayout = new javax.swing.GroupLayout(tituloPanel);
        tituloPanel.setLayout(tituloPanelLayout);
        tituloPanelLayout.setHorizontalGroup(
            tituloPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tituloPanelLayout.createSequentialGroup()
                .addGap(290, 290, 290)
                .addGroup(tituloPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tituloPanelLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel2))
                    .addComponent(jLabel1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        tituloPanelLayout.setVerticalGroup(
            tituloPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tituloPanelLayout.createSequentialGroup()
                .addContainerGap(7, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addGap(21, 21, 21))
        );

        producto1.setBackground(new java.awt.Color(204, 204, 204));
        producto1.setForeground(new java.awt.Color(153, 153, 153));
        producto1.setPreferredSize(new java.awt.Dimension(200, 350));

        jLabel3.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel3.setText("Cafeteria FIQ");

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fiq.jpeg"))); // NOI18N
        jLabel11.setText("s");
        jLabel11.setToolTipText("");

        javax.swing.GroupLayout imgFIQLayout = new javax.swing.GroupLayout(imgFIQ);
        imgFIQ.setLayout(imgFIQLayout);
        imgFIQLayout.setHorizontalGroup(
            imgFIQLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, imgFIQLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );
        imgFIQLayout.setVerticalGroup(
            imgFIQLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(imgFIQLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButton1.setText("Votar");

        jLabel6.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel6.setText("Votos:");

        iFIQ.setText("jLabel6");

        javax.swing.GroupLayout producto1Layout = new javax.swing.GroupLayout(producto1);
        producto1.setLayout(producto1Layout);
        producto1Layout.setHorizontalGroup(
            producto1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(producto1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(imgFIQ, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(producto1Layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, producto1Layout.createSequentialGroup()
                .addContainerGap(73, Short.MAX_VALUE)
                .addGroup(producto1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(producto1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(iFIQ, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(68, 68, 68))
        );
        producto1Layout.setVerticalGroup(
            producto1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(producto1Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(producto1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(iFIQ))
                .addGap(14, 14, 14)
                .addComponent(imgFIQ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        iFIQ.getAccessibleContext().setAccessibleName("FIQ");

        producto2.setBackground(new java.awt.Color(204, 204, 204));
        producto2.setPreferredSize(new java.awt.Dimension(218, 344));

        jLabel4.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel4.setText("Cafeteria FMAT");

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fmat.jpeg"))); // NOI18N
        jLabel10.setText("d");

        javax.swing.GroupLayout imgFMATLayout = new javax.swing.GroupLayout(imgFMAT);
        imgFMAT.setLayout(imgFMATLayout);
        imgFMATLayout.setHorizontalGroup(
            imgFMATLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(imgFMATLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );
        imgFMATLayout.setVerticalGroup(
            imgFMATLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(imgFMATLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButton2.setText("Votar");

        jLabel7.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel7.setText("Votos:");

        iFMAT.setText("jLabel6");

        javax.swing.GroupLayout producto2Layout = new javax.swing.GroupLayout(producto2);
        producto2.setLayout(producto2Layout);
        producto2Layout.setHorizontalGroup(
            producto2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(producto2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(imgFMAT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, producto2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(71, 71, 71))
            .addGroup(producto2Layout.createSequentialGroup()
                .addGroup(producto2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(producto2Layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(jLabel4))
                    .addGroup(producto2Layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(iFMAT, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(67, Short.MAX_VALUE))
        );
        producto2Layout.setVerticalGroup(
            producto2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(producto2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(producto2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(iFMAT))
                .addGap(14, 14, 14)
                .addComponent(imgFMAT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        producto3.setBackground(new java.awt.Color(204, 204, 204));
        producto3.setPreferredSize(new java.awt.Dimension(218, 344));

        jLabel5.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel5.setText("Cafeteria FI");

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fi.jpeg"))); // NOI18N
        jLabel9.setText("a");

        javax.swing.GroupLayout imgFiLayout = new javax.swing.GroupLayout(imgFi);
        imgFi.setLayout(imgFiLayout);
        imgFiLayout.setHorizontalGroup(
            imgFiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, imgFiLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 226, Short.MAX_VALUE)
                .addContainerGap())
        );
        imgFiLayout.setVerticalGroup(
            imgFiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(imgFiLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(8, Short.MAX_VALUE))
        );

        jButton3.setText("Votar");

        jLabel8.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel8.setText("Votos:");

        iFI.setText("jLabel6");

        javax.swing.GroupLayout producto3Layout = new javax.swing.GroupLayout(producto3);
        producto3.setLayout(producto3Layout);
        producto3Layout.setHorizontalGroup(
            producto3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(producto3Layout.createSequentialGroup()
                .addGroup(producto3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(producto3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(imgFi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(producto3Layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(producto3Layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addGroup(producto3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(producto3Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(iFI, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel5))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        producto3Layout.setVerticalGroup(
            producto3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(producto3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(producto3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(iFI))
                .addGap(13, 13, 13)
                .addComponent(imgFi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        btnVGraficoBarra.setText("Gráfico de Barras");
        btnVGraficoBarra.setMaximumSize(new java.awt.Dimension(120, 23));
        btnVGraficoBarra.setMinimumSize(new java.awt.Dimension(120, 23));
        btnVGraficoBarra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVGraficoBarraActionPerformed(evt);
            }
        });

        btnVGraficoPastel.setText("Gráfico de Pastel");

        javax.swing.GroupLayout contenidoLayout = new javax.swing.GroupLayout(contenido);
        contenido.setLayout(contenidoLayout);
        contenidoLayout.setHorizontalGroup(
            contenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tituloPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, contenidoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(producto1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(producto2, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(producto3, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(contenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnVGraficoBarra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnVGraficoPastel))
                .addGap(7, 7, 7))
        );
        contenidoLayout.setVerticalGroup(
            contenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contenidoLayout.createSequentialGroup()
                .addComponent(tituloPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(contenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(contenidoLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(contenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(producto3, javax.swing.GroupLayout.DEFAULT_SIZE, 335, Short.MAX_VALUE)
                            .addComponent(producto2, javax.swing.GroupLayout.DEFAULT_SIZE, 335, Short.MAX_VALUE)
                            .addComponent(producto1, javax.swing.GroupLayout.DEFAULT_SIZE, 335, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(contenidoLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnVGraficoPastel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnVGraficoBarra, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(160, 160, 160))))
        );

        tituloPanel.getAccessibleContext().setAccessibleName("titulo");
        tituloPanel.getAccessibleContext().setAccessibleDescription("");
        btnVGraficoPastel.getAccessibleContext().setAccessibleName("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(contenido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(contenido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVGraficoBarraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVGraficoBarraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnVGraficoBarraActionPerformed

   
    
     private void inicializarProductos() {
        // Obtener los nombres y contadores de los productos
        List<String> nombresProductos = controlador.obtenerNombresProductos();
        Map<String, Integer> datosProductos = controlador.obtenerDatosProductos();

        // Producto 1
        if (nombresProductos.size() > 0) {
            String nombreProducto1 = nombresProductos.get(0);
            int contadorVotos1 = datosProductos.get(nombreProducto1);

            jLabel3.setText(nombreProducto1);
            etiquetasContadores.put(nombreProducto1, iFIQ);
            iFIQ.setText(String.valueOf(contadorVotos1));

            jButton1.addActionListener(new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent e) {
                    controlador.procesarVoto(nombreProducto1);
                    controlador.registrarEnBitacora("App.inicializarProdcutos()", "Se proceso el voto para "+ nombreProducto1);
                }
            });
        }

        // Producto 2
        if (nombresProductos.size() > 1) {
            String nombreProducto2 = nombresProductos.get(1);
            int contadorVotos2 = datosProductos.get(nombreProducto2);

            jLabel4.setText(nombreProducto2);
            etiquetasContadores.put(nombreProducto2, iFMAT);
            iFMAT.setText(String.valueOf(contadorVotos2));

            jButton2.addActionListener(new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent e) {
                    controlador.procesarVoto(nombreProducto2);
                    controlador.registrarEnBitacora("App.inicializarProdcutos()", "Se proceso el voto para "+ nombreProducto2);

                }
            });
        }

        // Producto 3
        if (nombresProductos.size() > 2) {
            String nombreProducto3 = nombresProductos.get(2);
            int contadorVotos3 = datosProductos.get(nombreProducto3);

            jLabel5.setText(nombreProducto3);
            etiquetasContadores.put(nombreProducto3, iFI);
            iFI.setText(String.valueOf(contadorVotos3));

            jButton3.addActionListener(new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent e) {
                    controlador.procesarVoto(nombreProducto3);
                    controlador.registrarEnBitacora("App.inicializarProdcutos()", "Se proceso el voto para "+ nombreProducto3);

                }
            });
        }
        
        controlador.registrarEnBitacora("App.inicializarProductos()", "Se inicializaron los productos correctamente");
    }
    
    // Método para actualizar la vista con los datos actualizados
    public void actualizarVista(Map<String, Integer> datosProductos) {
        for (Map.Entry<String, Integer> entrada : datosProductos.entrySet()) {
            String nombreProducto = entrada.getKey();
            int contadorVotos = entrada.getValue();
            JLabel etiquetaContador = etiquetasContadores.get(nombreProducto);
            if (etiquetaContador != null) {
                etiquetaContador.setText(String.valueOf(contadorVotos));
            }
        }
    }
    
    private void agregarAccionesBotonesGraficas() {
    btnVGraficoBarra.addActionListener(new ActionListener() {
        @Override
        public void actionPerformed(ActionEvent e) {
            controlador.mostrarVentanaGraficoBarras();
            controlador.registrarEnBitacora("App.agregarAccionesBotonesGraficas()", "Se muestra el grafico de barras");

        }
    });

    btnVGraficoPastel.addActionListener(new ActionListener() {
        @Override
        public void actionPerformed(ActionEvent e) {
            controlador.mostrarVentanaGraficoPastel();
            controlador.registrarEnBitacora("App.agregarAccionesBotonesGraficas()", "Se muestra el grafico de Pastel");

        }
    });
}


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnVGraficoBarra;
    private javax.swing.JButton btnVGraficoPastel;
    private javax.swing.JPanel contenido;
    private javax.swing.JLabel iFI;
    private javax.swing.JLabel iFIQ;
    private javax.swing.JLabel iFMAT;
    private javax.swing.JPanel imgFIQ;
    private javax.swing.JPanel imgFMAT;
    private javax.swing.JPanel imgFi;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel producto1;
    private javax.swing.JPanel producto2;
    private javax.swing.JPanel producto3;
    private javax.swing.JPanel tituloPanel;
    // End of variables declaration//GEN-END:variables
}
